/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseStart();
		
		public void raiseAlma();
		
		public void raiseBarack();
		
		public long getElsoIdo();
		
		public void setElsoIdo(long value);
		
		public long getMasodikIdo();
		
		public void setMasodikIdo(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
